var x = 500;
var y = 500;
var dirX;
var dirY;
var plaeyrWidth;
var plaeyrHeight;
var playerImg;
var speed = 6;
var deg = 4;
var sight_x = 200;
var sight_y = 200;
var scale = 0.1;
var SprFrames = 0;
var currentFrame = 0;
var shoot = false;
var rot = 0;
var row = Math.floor(currentFrame / frames);
var col = Math.floor(currentFrame % frames);
var stop = false;
var sider = false;
var spiderCurrentFrame = 0;
var SpiderFrames = 10;
var spiderX = 50;
var spiderY = 50;
var spiderHeight = 0;
var angle = 0;
var spidersObj=[];
var SpAngle=0;