//VARIABLE
var sight_x;
var sight_y;
const UPDATE_TIME = 1000 / 50;
var timer = null;
var canvas;
var ctx;
var scale = 0.1;
var ufoObjects = [];
var speed = 1;
var sightSizeX = sight.width * scale;
var sightSizeY = sight.height * scale;
var score = 0;
var hit;
var load; 
var flame=[];
var hitX;
var hitY;
var frames = 20;
currentFrame = 0;
var row;
var col;
var ufoCuantity = 9850;
var bulletCount;
var ufoCounter = 0;
var Prise;
var BoxX;
var BoxY;
var getPrise;
var time = 0;
var Boxhit;
var bulletWidth;
var weapCoef;
var weapons;
var shootgunBullet;
